### ISSUE TITLE
Verify 17.9 has a breaking change

### ISSUE THREAD

**Issue by 304NotModified** [VerifyTests/Verify#589]
Unfortunately Verify 17.9 has a breaking change. 

The dependency of DiffEngine is moved from 9 to 10.  

This works in 17.8.x and breaks (binary and on build) with 17.9:

```c#
DiffTools.AddTool(
    name: name,
    exePath: vsDiffPath,
    targetLeftArguments: launchArguments,
    targetRightArguments: launchArguments
    requiresTarget: true, autoRefresh: true, isMdi: true, supportsText: true, binaryExtensions: new List<string>()
);
```

Will give: 

> Error CS1739: The best overload for 'AddTool' does not have a parameter named 'targetLeftArguments'

I assumed this library is following  [semver](https://semver.org/). If so. please make only breaking changes in Major versions :)
